Lab 1
vaskers5/Lost-NFT-Gallery pull request #1
Opened 2022-10-10 11:45 UTC by vaskers5

2022-10-10 12:18 UTC, BakasaRus requested changes
1. Добавить кусок кода
2. `<main/>` и `<footer/>`
3. `<section/>` / `<aside/>` / `<article/>`
4. Формула с надстрочными/подстрочными символами
5. Списки всякие разные
6. Полужирный/курсивный/зачёркнутый/подчёркнутый текст
7. Изучить вопросы семантики в целом

2022-10-10 12:18 UTC, BakasaRus commented on index.html
> +"
Какой-то мусор

2022-10-10 12:18 UTC, BakasaRus commented on index.html
> +                <a class="hero_link" href="https://t.me/Kazancev_Danil">
Лучше открывать в новой вкладке

2022-11-02 19:25 UTC, vaskers5 commented on index.html
> +                <a class="hero_link" href="https://t.me/Kazancev_Danil">
fixed

2022-11-02 19:26 UTC, vaskers5 commented on index.html
> +"
fixed

2022-11-02 20:12 UTC, vaskers5 commented
> 1. Добавить кусок кода
> 2. `<main/>` и `<footer/>`
> 3. `<section/>` / `<aside/>` / `<article/>`
> 4. Формула с надстрочными/подстрочными символами
> 5. Списки всякие разные
> 6. Полужирный/курсивный/зачёркнутый/подчёркнутый текст
> 7. Изучить вопросы семантики в целом

fixed

2022-11-07 12:59 UTC, BakasaRus approved these changes

2022-11-21 12:19 UTC, merged